name: Native build with Gradle

on:
  push:
    branches: [ "main" ]

env:
  JAVA_VERSION: '17'
  GRAALVM_VERSION: '22.3.2'
  GRAALVM_COMPONENTS: 'native-image'

permissions:
  contents: read

jobs:
  build_native:
    name: Build and test native application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ env.GRAALVM_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          components: ${{ env.GRAALVM_COMPONENTS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          check-for-updates: 'true'
      - uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: nativeTest nativeDistZip installNativeDist
      - uses: actions/upload-artifact@v3
        with:
          name: command_line_quickstart_native_${{ github.sha }}
          path: build/install/spring_command_line_quickstart-native
